# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f876e16bccaa4fde7a60c0d8cefd7caae57f8a9d677ca0ecad3bbdc3914dd8dbf9cab57eb5f91ea33ab9bf1d02b31a07cf079b8ed5e38d93fc1f2f15dbce794

test:
  secret_key_base: da2e72924315fd224ddd7cebc991a81b63aaba4108906f043f0aa95163895b68e2f6cb6f15ea2c626a0aa532cb62e3e3313998e8fc35a9981b87c17907a063ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
